# Generated by Django 6.0.5 on 2026-06-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_bio_profile_birth_date_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(choices=[('F', 'Filipino'), ('D', 'Dual Citizenship')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='citizenship_acquisition',
            field=models.CharField(blank=True, choices=[('B', 'By Birth'), ('N', 'By Naturalization')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('SEP', 'Separated'), ('O', 'Others')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dual_citizenship_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='house_block_lot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_extension',
            field=models.CharField(blank=True, help_text='e.g., Jr., Sr., III', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_skills_hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subdivision_village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, verbose_name='Sex at Birth'),
        ),
        migrations.CreateModel(
            name='CivilServiceEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_type', models.CharField(help_text='e.g., Career Service, RA 1080', max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('HS', 'High School'), ('COL', 'College'), ('VOC', 'Vocational/Technical'), ('MAS', "Master's Degree"), ('DOC', 'Doctorate Degree')], max_length=3)),
                ('school_name', models.CharField(max_length=255)),
                ('degree_finished', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_hours', models.PositiveIntegerField()),
                ('training_type', models.CharField(help_text='Managerial, Supervisory, Technical, etc.', max_length=100)),
                ('sponsor', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VoluntaryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('number_of_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=150)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntary_works', to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently employed', null=True)),
                ('position_title', models.CharField(max_length=150)),
                ('company_agency', models.CharField(max_length=255)),
                ('status_of_appointment', models.CharField(max_length=100)),
                ('government_service', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='blog.profile')),
            ],
        ),
    ]
