# Generated by Django 6.0.5 on 2026-06-15 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile_barangay_profile_citizenship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipAcqLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'pds_lu_citizenship_acquisition',
            },
        ),
        migrations.CreateModel(
            name='CitizenshipLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'pds_lu_citizenship',
            },
        ),
        migrations.CreateModel(
            name='CivilStatusLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'pds_lu_civil_status',
            },
        ),
        migrations.CreateModel(
            name='EducationLevelLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'pds_lu_education_level',
            },
        ),
        migrations.CreateModel(
            name='GenderLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'pds_lu_gender',
            },
        ),
        migrations.AlterField(
            model_name='civilserviceeligibility',
            name='eligibility_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='civilserviceeligibility',
            name='license_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short description', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='citizenship_acquisition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civil_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='training_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='civilserviceeligibility',
            table='pds_civil_service',
        ),
        migrations.AlterModelTable(
            name='education',
            table='pds_educational_background',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='pds_personal_information',
        ),
        migrations.AlterModelTable(
            name='trainingprogram',
            table='pds_learning_development',
        ),
        migrations.AlterModelTable(
            name='voluntarywork',
            table='pds_voluntary_work',
        ),
        migrations.AlterModelTable(
            name='workexperience',
            table='pds_work_experience',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_block_lot', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('subdivision_village', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pds_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pds_addresses',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='citizenship_acquisition_3nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.citizenshipacqlookup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='citizenship_3nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.citizenshiplookup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='civil_status_3nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.civilstatuslookup'),
        ),
        migrations.AddField(
            model_name='education',
            name='level_3nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.educationlevellookup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_3nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.genderlookup'),
        ),
    ]
