# Generated by Django 6.0.5 on 2026-06-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_citizenshipacqlookup_citizenshiplookup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city_municipality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house_block_lot',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subdivision_village',
        ),
    ]
