# Generated by Django 6.0.5 on 2026-06-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_transfer_pds_data_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='citizenship_acquisition',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
