# Generated by Django 6.0.5 on 2026-06-17 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_education_level_remove_profile_citizenship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='special_skills_hobbies',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Permanent', 'Permanent')], default='Residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pds_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpecialSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_skills', to='blog.profile')),
            ],
            options={
                'db_table': 'pds_special_skills',
            },
        ),
    ]
