# Generated by Django 6.0.5 on 2026-06-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_profile_number_of_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='number_of_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
